### ISSUE TITLE
Cluster name cannot contain underscore

### ISSUE THREAD

**Issue by JeffGiroux** [f5devcentral/f5-volterra-labs-101#100]
**Environment**
***Pick one, delete the rest***
- UDF Blueprint
- Application Lab

**Describe the bug**
Cluster name cannot contain underscores. In the lab guide, the example shows this...

```
Cluster Name | [unique name]_udf
```

If you use that as a cluster name in the UDF VoltMesh node, you get an error.

```
Field must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character!.
```

**To Reproduce**
1. Go to 'Exercise 4: Configure Site using Site UI'
2. Create Cluster Name with '_' (underscore) in name
3. See error

To note, the screenshot in 'Exercise 5: Accept Registration' has the correct cluster name with a hyphen '-' and not underscore.

**Comment by chen23** [comment]
fixed.  thanks @JeffGiroux
