### ISSUE TITLE
Create AWS VPC Site - Wrong Navigation Item

### ISSUE THREAD

**Issue by codygreen** [f5devcentral/f5-volterra-labs-101#102]
**Environment**
- Application Lab

**Describe the bug**
Exercise 4.1 tells you to navigate to Cloud Credentials instead of AWS VPC Sites

**Comment by chen23** [comment]
also reported by @JeffGiroux  fixed in b910bb287deff4abdbd932032cdd4391be8edac3

**Comment by JeffGiroux** [comment]
Also found in this section too...

Exercise 1: Tag AWS Site
1. In VoltConsole switch to the System context.
2. Navigate the menu to go to “Manage”->”Site Management” and click on “Cloud Credentials”.

Needs to be Manage -> Site Management -> AWS VPC Sites

At lab guide location...
/state3/vsite.html
