### ISSUE TITLE
Create internal LB workflow prematurely closes origin pool window

### ISSUE THREAD

**Issue by JeffGiroux** [f5devcentral/f5-volterra-labs-101#104]
**Environment**
***Pick one, delete the rest***
- Application Lab

**Describe the bug**
This step in the lab guide says to close the origin pool dialogue but you need it to remain open to follow the proceeding AWS workload members to be added.

file: state4/internallb.rst

Around this step...
Exercise 3: Configure Second Origin Pool (for AWS)

The previous step says to "8. Click the Continue button to close the “Origin Pool” dialogue" but if you do that then you can't do the exact steps proceeding. Step 8 needs to be removed. Otherwise, the student will need to finish the internal-lb remaining steps, then save and exit. Once that is finished, student will need to open the origin pool "Edit" screen for the new brews-inventory origin pool and add a new origin server item.

**To Reproduce**
1. Go to 'state4/internallb.html'
2. Create internal lb, and start creating pool via lab guide
3. Lab guide says to close original pool window after adding UDF pool only
4. Then lab guide says to add additional AWS workload as new origin pool but you cannot since the window is closed and you are now in the LB window.

**Expected behavior**
n/a

**Screenshots**

**Additional context**
Remove this line

8. Click the Continue button to close the “Origin Pool” dialogue.

**Comment by chen23** [comment]
also reported in #107 fixed in b40188bef73e0e8e9f8b6a851cd1113836984a94
