### ISSUE TITLE
screenshot out of order Exercise 2: Create Virtual K8s Workload

### ISSUE THREAD

**Issue by JeffGiroux** [f5devcentral/f5-volterra-labs-101#105]
**Environment**
***Pick one, delete the rest***
- Application Lab

**Describe the bug**
The screenshot for "Customer Virtual Sites" is not directly under the step for "Under Customer Virtual Sites, click the Configure link." which currently is step 8.

_images/vk8s_workloads_advertise.png

Currently this screenshot showing both the Customer Virtual Site GUI option and the Advertise GUI option. Would prefer to see this screenshot split into two. That way, the Customer Virtual Site portion of the pic can be placed under step 8. The Advertise portion of the screenshot can be placed under step 11 as it is currently listed.

**Comment by chen23** [comment]
updated in a8ce94542a26ed92620e054b90eaaa66a221459f
