### ISSUE TITLE
Small errors in the "Lab Guide - Appliaction"

### ISSUE THREAD

**Issue by ncartron** [f5devcentral/f5-volterra-labs-101#107]
**Environment**
- UDF Blueprint

**Describe the bug**
Hi team, just finished the 101-lab and enjoyed it a lot, super fun and it covers A LOT of what can be done with Volterra, touching deployment across public cloud / private site, adding things/features/elements step by step, really liked it!

I have noted a few errors/typos/things to improve in the "Lab Guide - Application", which I am listing below:

1. `Virtual Site` section: 
- "2. Navigate the menu to go to “Manage”->”Site Management” and click on “Cloud Credentials”."
  Should be 
  "Navigate the menu to go to “Manage”->”Site Management” and click on **“AWS VPC Site”**"

2. `Update Origin Pools` section:
- "Exercise 3: Check HTTP LB Origin Servers"
The 3rd Origin server will only appear once there is traffic going through it, so we should add a step where the student generates some traffic on the Brew SPA.

3. `Internal HTTP Load Balancer` section:
- "Exercise 3: Configure Second Origin Pool (for AWS)"
The last step of previous exercise (“Exercise 2: Configure Origin Server (for UDF)”) ends with “8.Click the Continue button to close the “Origin Pool” dialogue.”
This is wrong as the student must stay in the origin pool form to add another origin pool

**Comment by chen23** [comment]
fixed in b40188bef73e0e8e9f8b6a851cd1113836984a94
