### ISSUE TITLE
New vk8s workload dialog page has an updated Deploy Options section

### ISSUE THREAD

**Issue by honghuac** [f5devcentral/f5-volterra-labs-101#110]
**Environment**
- Application Lab

**Describe the bug**
**_New vk8s workload_** dialog page has an updated **_Deploy Options_** section.

**To Reproduce**
1. Go to both **Exercise 3: Create Virtual K8s Workload for the API** and **Exercise 2: Create Virtual K8s Workload for the Single-page App** of  'Virtual Kubernetes' lab sheet
2. At step 7 'Enter the following variables in the Deploy Options section.'
3. Add this attached screenshot
4. Update the variable 'Where to Deploy the workload' to 'Deploy Options'
5. Go to **Deploy the “Recommendations” Service.** lab sheet. Look for the section **Exercise 2: Deploy the “Recommendations” Workload**.
6. At step **6. Enter the following variables in the Deploy Options section.**, add this attached screenshot.
7. Update the variable 'Where to Deploy the workload' to 'Deploy Options'

**Screenshots**
![whereto](https://user-images.githubusercontent.com/8625482/113511716-db7c0000-9593-11eb-8092-79fc322d0297.PNG)

**Additional context**
Love the labs!

**Comment by chen23** [comment]
updated in a8ce94542a26ed92620e054b90eaaa66a221459f
