### ISSUE TITLE
New: vK8s workload dialog page has an updated Select Port to Advertise section

### ISSUE THREAD

**Issue by honghuac** [f5devcentral/f5-volterra-labs-101#111]
**Environment**
- Application Lab

**Describe the bug**
New: vK8s workload dialog page has an updated Select Port to Advertise section.

**To Reproduce**
1. Go to 'Virtual Kubernetes' lab sheet
2. Go to step 12 'Enter the following variables:'
3. Change respective Variable names to 'Port Information' as shown in the attached screenshot.

**Screenshots**
![ports](https://user-images.githubusercontent.com/8625482/113511939-ea16e700-9594-11eb-8504-9c607015d9cf.PNG)

**Additional context**
Love the labs!

**Comment by chen23** [comment]
updated in 40edf0191eb409e5b75c396ff7de2425a3597198
