### ISSUE TITLE
Virtual Kubernetes Lab, "In this section we will create an additional Virtual K8s workload.", reference to “Edit" button should be updated.

### ISSUE THREAD

**Issue by honghuac** [f5devcentral/f5-volterra-labs-101#112]
**Environment**
- Application Lab

**Describe the bug**
In Virtual Kubernetes Lab with instruction "In this section we will create an additional Virtual K8s workload", reference to “Edit" button should be updated.

**To Reproduce**
1. Go to the line 'Step 11. Under Advertise Option, choose Advertise In Cluster. Click the “Edit button.'
2. Change the word "Edit to "Configure"

**Comment by chen23** [comment]
updated in a8ce94542a26ed92620e054b90eaaa66a221459f
