### ISSUE TITLE
Add Virtual Site screenshot needs updating - Deploy the “Recommendations” Service Lab

### ISSUE THREAD

**Issue by honghuac** [f5devcentral/f5-volterra-labs-101#113]
**Environment**
- Application Lab

**Describe the bug**
Add Virtual Site screenshot needs updating - Deploy the “Recommendations” Service Lab

**To Reproduce**
1. Go to 'Exercise 1: Create a Virtual Site with our target REs' 
2. Locate 'Step 3. Fill out the form.'
2. Replace Add Virtual Site screenshot with the attached.

**Screenshots**
![avs](https://user-images.githubusercontent.com/8625482/113514121-6ca4a400-959f-11eb-8940-eeb9ac0280a1.PNG)

**Additional context**
Love the labs!

**Comment by chen23** [comment]
updated in 1c8a336ccfd2c54d8ae74f80e08db17ab033956c.

Thank You @honghuac!
