### ISSUE TITLE
use "generic" tenant in lab guide

### ISSUE THREAD

**Issue by chen23** [f5devcentral/f5-volterra-labs-101#119]
**Environment**
***Pick one, delete the rest***
- Security Lab

@lesleycw 

**Describe the bug**
The lab guide assumes that the student is using the amer-ent tenant.  It should be generic since it could be a different tenant.

**Comment by lesleycw** [comment]
This is addressed in Steps 1-3 of Task 3,  where the language is generic. The only specific tenant mention is in the graphic which can be changed.  The other piece is the specific mention for DNS.   Would that suffice?

**Comment by lesleycw** [comment]
Added localization to lab guide. Removed specific references
