### ISSUE TITLE
do not use HTTPS sites for lab

### ISSUE THREAD

**Issue by chen23** [f5devcentral/f5-volterra-labs-101#120]
**Environment**
- Security Lab

@lesleycw 

**Describe the bug**

Do not use HTTPS sites for creating LB resources.  There are API limits on Let's Encrypt.  HTTP for lab purposes is preferred.

**Comment by lesleycw** [comment]
We can change this though I think we need to better document it

**Comment by lesleycw** [comment]
Removed HTTPS resource - changed to HTTP
