### ISSUE TITLE
state1/httplb 

### ISSUE THREAD

**Issue by kreynoldsf5** [f5devcentral/f5-volterra-labs-101#29]
I'm concerned that participants won't be able to finish this in the timeout period.

Is there a natural breaking point?

**Comment by kreynoldsf5** [comment]
I just walked through this again. I think this is going to inception level confusing for students.

I propose the following workflow:
- Create all necessary Origin pools and related config first.
- Create the HTTP LB.
- Assign the default.
- Create the routes and attach each pool as needed.

**Comment by codygreen** [comment]
section 2 split into 2 new sections
