### ISSUE TITLE
update screenshots with consistent App namespace

### ISSUE THREAD

**Issue by kreynoldsf5** [f5devcentral/f5-volterra-labs-101#31]
I believe the students will better be able to follow the workflows if the example namespaces were consistent throughout the lab.

I've created a "labuser" namespace in the GSA tenant for this purpose. 

I've grabbed SS for prework and state1. State 4 should be fine. That just leaves state3 and 2.

**Comment by kreynoldsf5** [comment]
@hooolio,

There is an 'labuser' namespace in the GSA tenant. I'll wipe it clean so you can use that for screenshots while you walk through.

**Comment by salinaf5** [comment]
All lab guides have been updated with labuser as the example namespace.
