### ISSUE TITLE
state2/tcpLb

### ISSUE THREAD

**Issue by kreynoldsf5** [f5devcentral/f5-volterra-labs-101#32]
There seems to be steps missing while configuring the TCP load balancer. 

After step 4, there is no 'domains' section to configure.

**Comment by kreynoldsf5** [comment]
I'm not sure if this is related -- but there is an ordering problem here, too.

This step occurs before the 'create a virtual site' step. It appears the virtual site you are to create after this is referenced in this step.

Should this step happen after vitual site creation?

**Comment by kreynoldsf5** [comment]
Another/related ordering problem. 

This step suggests you select an origin pool that's not yet been created.

**Comment by codygreen** [comment]
this was reworked.
