### ISSUE TITLE
Site Spanning will only send traffic to UDF site and not AWS

### ISSUE THREAD

**Issue by chen23** [f5devcentral/f5-volterra-labs-101#37]
**Environment**
- Application Lab

**Describe the bug**

In the "Site Spanning" section.

When you create additional pools for SPA/API it will default traffic to only one pool and not both.

Current workaround is to add site to existing pool instead of creating a new pool.

**Comment by chen23** [comment]
This also requires that spa listen on 8081 in both sites (vs. using port mapping).  it is not possible to have a pool with pool members that use different ports.  https://github.com/f5devcentral/spa-demo-app/pull/27

**Comment by codygreen** [comment]
this has been resolved since we are now using one origin pool per service.
