### ISSUE TITLE
MongoDB is exposed to internet

### ISSUE THREAD

**Issue by chen23** [f5devcentral/f5-volterra-labs-101#39]
**Environment**
- Application Lab

**Describe the bug**
When you expose the MongoDB service it is exposed on the EIP of the Volterra GW.  Applying a Network Policy can restrict access.

**To Reproduce**

Deploy TCP LB for MongoDB.  Retrieve EIP of Volterra GW.

```
$ curl [EIP]:27017
It looks like you are trying to access MongoDB over HTTP on the native driver port.
```
**Expected behavior**

Traffic should not be exposed.

**Comment by chen23** [comment]
Sample Network Policy that blocks traffic.

![image](https://user-images.githubusercontent.com/63689/110319654-32b2a300-7fdd-11eb-966c-ae30396dcbc4.png)

Applying to AWS site

![image](https://user-images.githubusercontent.com/63689/110319676-3c3c0b00-7fdd-11eb-88af-6f99c67909ff.png)

Traffic blocked

```
$ curl [EIP]:27017 -m 3
curl: (28) Connection timed out after 3004 milliseconds
```

**Comment by codygreen** [comment]
We will need to add a similar network policy for the inventory url

**Comment by kreynoldsf5** [comment]
In order to prevent additional work, can we capture these screenshots using a generic 'labuser' naming scheme?

**Comment by chen23** [comment]
I have not tested the policy to see whether it still allows access from inventory. May need to add 100.64.x.z for VoltStack network. It is applied at the site so in theory applies for both tcp and internal http vips.
