### ISSUE TITLE
 remove registry password from documentation

### ISSUE THREAD

**Issue by chen23** [f5devcentral/f5-volterra-labs-101#82]
**Environment**
- Application Lab

**Describe the bug**
remove /change registry password from documentation

currently the registry password is embedded in the lab documentation that is public on GitHub.  ideally it should be on the main documentation page (inside of UDF) 

the resources in the registry are public [spa-demo-app](https://github.com/f5devcentral/spa-demo-app) but it would be better to remove in case resources are non-public in the future

**Comment by kreynoldsf5** [comment]
I've updated the registry to implement an ACL. 

The 'labuser' creds in the lab guide can now only pull. "Push" is reserved for an admin user which is not specified. 

I also "refreshed" the containers out there in case something got pushed earlier. Reg is totally fresh build from latest spa-demo-app.

closing #82.
